### ISSUE TITLE
Allow users to disable comments on own post

### ISSUE THREAD

**Issue by berkus** [FreeFeed/freefeed-html#19]

**Comment by kukutz** [comment]
User as author of his own posts (or an admin of a group) should have additional options at such posts. They are grouped in the Edit menu. This menu and "Edit" control itself shouldn't be visible to other users except author and group admin. If post were posted to personal feed and groups altogether, admins of these groups can set disable comments option for this post.

See picture: 
![2015-12-04 18-50-27](https://cloud.githubusercontent.com/assets/12851928/11593903/f3db04ac-9ab7-11e5-9169-e64e82f54eb2.png)

Here user can:
- Edit post text (only available if she is the actual author of the post, regardless of the group admin status)
- Moderate comments (this feature will be done in separate issue)
- Disable comments / Enable comments
- Delete the entry

When user clicks "Disable comments" it will render the post as the following: 
![2015-12-04 19-29-48](https://cloud.githubusercontent.com/assets/12851928/11594869/773e3ad0-9abd-11e5-816e-9bf2c9aa51ca.png)

Other users who are not author or group admin will see same _Comment disabled_ italic text, but without "(enable)" control. They also will not see "Comment" and "Add comment" links on post with disabled comments:
![2015-12-04 19-03-31](https://cloud.githubusercontent.com/assets/12851928/11594227/dfeaa9fa-9ab9-11e5-9713-c9418cfff4a6.png)

This restriction does not apply to the author of post: she will see "Comment" and "Add comment - disabled for others" controls and will be able to add comment.

**Comment by berkus** [comment]
(FF visuals should be different, e.g. no drop-down menus)

**Comment by kukutz** [comment]
Why no drop-down menus? Mulitword actions in one line will be very unusable as it seems to me.

For example:

an hour ago - Comment - Like - Edit - Disable comments - Delete

**Comment by urbansheep** [comment]
I agree with @kukutz. Drop-down menu is also another level of foolproofing against accidental deletion of posts, so all the extra management options — either destructive or non-essential — should rather stay out of the way and be collapsed until needed.

**Comment by urbansheep** [comment]
You can think of it in this way: when user sees a list of actions she is primed to act on it. Do we want to Like/Comment/Hide posts? Yes, it sort of is the essence of the flow.

Do we want a lot of threads to be locked down and unavailable to comment or deleted or losing comments all the time? Nah, not really.

But do we have to offer those options for when they're _really_ necessary? Yes, we do. And as a toll for their use (and to add friction) we can make them a bit more difficult to reach, by adding extra tap and menu.

**Comment by berkus** [comment]
We want to implement this drop-down way better than it was in friendfeed then, because i can remember more than one instance where I deleted post instead of disabling comments.

EDIT: current look on beta.ff.net is much more usable, thanks @clbn

**Comment by urbansheep** [comment]
There're two failsafe ways:
- Ask for confirmation (as BetterFeed does now).
- Provide an Undo for deleted posts/comments.

This makes it almost impossible to lose post/comment by mistake.

**Comment by clbn** [comment]
This is partly implemented in #23 and fully implemented in https://github.com/FreeFeed/freefeed-react-client/pull/162 (except for the functionality for group admins, which is going to be part of the other epic).
